# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:  
  organization: 'your-organization'  
  project: 'your-yuanxiao'  
  query_id: 'your-query-id'  # 或者直接使用查询的WIQL字符串（如果API支持）  
  
pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python testfile.py --organization $(organization) --project $(project) --query_id $(query_id) 
    python testfile.py --organization $(organization) --project $(project) --query_id $(query_id) 
  displayName: 'testfile'
