# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:  
  organization: 'https://dev.azure.com/ABB-BCI-PCP/'  
  project: 'PCP-Test'  

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python testfile.py $(organization) $(project) $(query_id) $(def_task_name) $(def_big_ver) $(def_sub_ver) 
    mkdir -p $(Build.ArtifactStagingDirectory)/output  
    mv output-Bug.csv $(Build.ArtifactStagingDirectory)/output/ 
  displayName: 'testfile'

- task: PublishBuildArtifacts@1  
  inputs:  
    PathtoPublish: 'output-Bug-$(task_name).csv'  
    ArtifactName: 'output-csv'  
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1  
  inputs:  
    PathtoPublish: 'output-Epic_Feature-$(task_name).csv'  
    ArtifactName: 'output-csv'  
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1  
  inputs:  
    PathtoPublish: 'feature_epic_log.txt'  
    ArtifactName: 'output-csv'  
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1  
  inputs:  
    PathtoPublish: 'bug_log.txt'  
    ArtifactName: 'output-csv'  
    publishLocation: 'Container'
    